// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org}\actions\hosted-runners\images\custom\{image_definition_id}\versions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VersionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GFlow.GitHub.orgs.item.actions.hostedRunners.images.custom.item.versions.item collection</summary>
        /// <param name="position">Version of a custom image</param>
        /// <returns>A <see cref="global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.Item.WithVersionItemRequestBuilder"/></returns>
        public global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.Item.WithVersionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("version", position);
                return new global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.Item.WithVersionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VersionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VersionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions", rawUrl)
        {
        }
        /// <summary>
        /// List image versions of a custom image for an organization.OAuth tokens and personal access tokens (classic) need the `manage_runners:org` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/rest/actions/hosted-runners#list-image-versions-of-a-custom-image-for-an-organization" />
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsGetResponse?> GetAsVersionsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsGetResponse> GetAsVersionsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsGetResponse>(requestInfo, global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List image versions of a custom image for an organization.OAuth tokens and personal access tokens (classic) need the `manage_runners:org` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/rest/actions/hosted-runners#list-image-versions-of-a-custom-image-for-an-organization" />
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsVersionsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsResponse>(requestInfo, global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List image versions of a custom image for an organization.OAuth tokens and personal access tokens (classic) need the `manage_runners:org` scope to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GFlow.GitHub.Orgs.Item.Actions.HostedRunners.Images.Custom.Item.Versions.VersionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VersionsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
