// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>
    /// Provides details of a custom runner image
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionsHostedRunnerCustomImage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the image. Use this ID for the `image` parameter when creating a new larger runner.</summary>
        public int? Id { get; set; }
        /// <summary>The latest image version associated with the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestVersion { get; set; }
#nullable restore
#else
        public string LatestVersion { get; set; }
#endif
        /// <summary>Display name for this image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The operating system of the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Platform { get; set; }
#nullable restore
#else
        public string Platform { get; set; }
#endif
        /// <summary>The image provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The number of image versions associated with the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Total size of all the image versions in GB.</summary>
        public int? TotalVersionsSize { get; set; }
        /// <summary>The number of image versions associated with the image.</summary>
        public int? VersionsCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Models.ActionsHostedRunnerCustomImage"/> and sets the default values.
        /// </summary>
        public ActionsHostedRunnerCustomImage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.ActionsHostedRunnerCustomImage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.ActionsHostedRunnerCustomImage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.ActionsHostedRunnerCustomImage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "latest_version", n => { LatestVersion = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "total_versions_size", n => { TotalVersionsSize = n.GetIntValue(); } },
                { "versions_count", n => { VersionsCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("latest_version", LatestVersion);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("platform", Platform);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("state", State);
            writer.WriteIntValue("total_versions_size", TotalVersionsSize);
            writer.WriteIntValue("versions_count", VersionsCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
