// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionsRuleRestrictActionsActors_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "restrict_actions_actors")]
        #pragma warning disable CS1591
        Restrict_actions_actors,
        #pragma warning restore CS1591
    }
}
