// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ArtifactDeploymentRecord_runtime_risks
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "critical-resource")]
        #pragma warning disable CS1591
        CriticalResource,
        #pragma warning restore CS1591
        [EnumMember(Value = "internet-exposed")]
        #pragma warning disable CS1591
        InternetExposed,
        #pragma warning restore CS1591
        [EnumMember(Value = "lateral-movement")]
        #pragma warning disable CS1591
        LateralMovement,
        #pragma warning restore CS1591
        [EnumMember(Value = "sensitive-data")]
        #pragma warning disable CS1591
        SensitiveData,
        #pragma warning restore CS1591
    }
}
