// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>The scope of the budget</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Budget_budget_scope
    {
        [EnumMember(Value = "enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization")]
        #pragma warning disable CS1591
        Organization,
        #pragma warning restore CS1591
        [EnumMember(Value = "repository")]
        #pragma warning disable CS1591
        Repository,
        #pragma warning restore CS1591
        [EnumMember(Value = "cost_center")]
        #pragma warning disable CS1591
        Cost_center,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi_user_customer")]
        #pragma warning disable CS1591
        Multi_user_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi_user_cost_center")]
        #pragma warning disable CS1591
        Multi_user_cost_center,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
    }
}
