// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>
    /// Configuration for code scanning default setup.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CodeScanningDefaultSetup : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Languages to be analyzed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_languages?>? Languages { get; set; }
#nullable restore
#else
        public List<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_languages?> Languages { get; set; }
#endif
        /// <summary>CodeQL query suite to be used.</summary>
        public global::GFlow.GitHub.Models.CodeScanningDefaultSetup_query_suite? QuerySuite { get; set; }
        /// <summary>Runner label to be used if the runner type is labeled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunnerLabel { get; set; }
#nullable restore
#else
        public string RunnerLabel { get; set; }
#endif
        /// <summary>Runner type to be used.</summary>
        public global::GFlow.GitHub.Models.CodeScanningDefaultSetup_runner_type? RunnerType { get; set; }
        /// <summary>The frequency of the periodic analysis.</summary>
        public global::GFlow.GitHub.Models.CodeScanningDefaultSetup_schedule? Schedule { get; set; }
        /// <summary>Code scanning default setup has been configured or not.</summary>
        public global::GFlow.GitHub.Models.CodeScanningDefaultSetup_state? State { get; set; }
        /// <summary>Threat model to be used for code scanning analysis. Use `remote` to analyze only network sources and `remote_and_local` to include local sources like filesystem access, command-line arguments, database reads, environment variable and standard input.</summary>
        public global::GFlow.GitHub.Models.CodeScanningDefaultSetup_threat_model? ThreatModel { get; set; }
        /// <summary>Timestamp of latest configuration update.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Models.CodeScanningDefaultSetup"/> and sets the default values.
        /// </summary>
        public CodeScanningDefaultSetup()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.CodeScanningDefaultSetup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.CodeScanningDefaultSetup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.CodeScanningDefaultSetup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "languages", n => { Languages = n.GetCollectionOfEnumValues<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_languages>()?.AsList(); } },
                { "query_suite", n => { QuerySuite = n.GetEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_query_suite>(); } },
                { "runner_label", n => { RunnerLabel = n.GetStringValue(); } },
                { "runner_type", n => { RunnerType = n.GetEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_runner_type>(); } },
                { "schedule", n => { Schedule = n.GetEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_schedule>(); } },
                { "state", n => { State = n.GetEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_state>(); } },
                { "threat_model", n => { ThreatModel = n.GetEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_threat_model>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_languages>("languages", Languages);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_query_suite>("query_suite", QuerySuite);
            writer.WriteStringValue("runner_label", RunnerLabel);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_runner_type>("runner_type", RunnerType);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_schedule>("schedule", Schedule);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_state>("state", State);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.CodeScanningDefaultSetup_threat_model>("threat_model", ThreatModel);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
