// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>Threat model to be used for code scanning analysis. Use `remote` to analyze only network sources and `remote_and_local` to include local sources like filesystem access, command-line arguments, database reads, environment variable and standard input.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CodeScanningDefaultSetup_threat_model
    {
        [EnumMember(Value = "remote")]
        #pragma warning disable CS1591
        Remote,
        #pragma warning restore CS1591
        [EnumMember(Value = "remote_and_local")]
        #pragma warning disable CS1591
        Remote_and_local,
        #pragma warning restore CS1591
    }
}
