// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConcurrencyGroup_group_members_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "in_progress")]
        #pragma warning disable CS1591
        In_progress,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
    }
}
