// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>
    /// An entry in the reviews log for environment deployments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvironmentApprovals : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comment submitted with the deployment review</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The list of environments that were approved or rejected</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GFlow.GitHub.Models.EnvironmentApprovals_environments>? Environments { get; set; }
#nullable restore
#else
        public List<global::GFlow.GitHub.Models.EnvironmentApprovals_environments> Environments { get; set; }
#endif
        /// <summary>Whether deployment to the environment(s) was approved or rejected or pending (with comments)</summary>
        public global::GFlow.GitHub.Models.EnvironmentApprovals_state? State { get; set; }
        /// <summary>A GitHub user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GFlow.GitHub.Models.SimpleUser? User { get; set; }
#nullable restore
#else
        public global::GFlow.GitHub.Models.SimpleUser User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Models.EnvironmentApprovals"/> and sets the default values.
        /// </summary>
        public EnvironmentApprovals()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.EnvironmentApprovals"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.EnvironmentApprovals CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.EnvironmentApprovals();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "environments", n => { Environments = n.GetCollectionOfObjectValues<global::GFlow.GitHub.Models.EnvironmentApprovals_environments>(global::GFlow.GitHub.Models.EnvironmentApprovals_environments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "state", n => { State = n.GetEnumValue<global::GFlow.GitHub.Models.EnvironmentApprovals_state>(); } },
                { "user", n => { User = n.GetObjectValue<global::GFlow.GitHub.Models.SimpleUser>(global::GFlow.GitHub.Models.SimpleUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("comment", Comment);
            writer.WriteCollectionOfObjectValues<global::GFlow.GitHub.Models.EnvironmentApprovals_environments>("environments", Environments);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.EnvironmentApprovals_state>("state", State);
            writer.WriteObjectValue<global::GFlow.GitHub.Models.SimpleUser>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
