// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>
    /// An item belonging to a project
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsV2ItemSimple : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time when the item was archived.</summary>
        public DateTimeOffset? ArchivedAt { get; set; }
        /// <summary>The content represented by the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content? Content { get; set; }
#nullable restore
#else
        public global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content Content { get; set; }
#endif
        /// <summary>The type of content tracked in a project item</summary>
        public global::GFlow.GitHub.Models.ProjectsV2ItemContentType? ContentType { get; set; }
        /// <summary>The time when the item was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>A GitHub user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GFlow.GitHub.Models.SimpleUser? Creator { get; set; }
#nullable restore
#else
        public global::GFlow.GitHub.Models.SimpleUser Creator { get; set; }
#endif
        /// <summary>The unique identifier of the project item.</summary>
        public double? Id { get; set; }
        /// <summary>The URL of the item in the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemUrl { get; set; }
#nullable restore
#else
        public string ItemUrl { get; set; }
#endif
        /// <summary>The node ID of the project item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeId { get; set; }
#nullable restore
#else
        public string NodeId { get; set; }
#endif
        /// <summary>The URL of the project this item belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectUrl { get; set; }
#nullable restore
#else
        public string ProjectUrl { get; set; }
#endif
        /// <summary>The time when the item was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Models.ProjectsV2ItemSimple"/> and sets the default values.
        /// </summary>
        public ProjectsV2ItemSimple()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.ProjectsV2ItemSimple"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.ProjectsV2ItemSimple CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.ProjectsV2ItemSimple();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived_at", n => { ArchivedAt = n.GetDateTimeOffsetValue(); } },
                { "content", n => { Content = n.GetObjectValue<global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content>(global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content.CreateFromDiscriminatorValue); } },
                { "content_type", n => { ContentType = n.GetEnumValue<global::GFlow.GitHub.Models.ProjectsV2ItemContentType>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creator", n => { Creator = n.GetObjectValue<global::GFlow.GitHub.Models.SimpleUser>(global::GFlow.GitHub.Models.SimpleUser.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "item_url", n => { ItemUrl = n.GetStringValue(); } },
                { "node_id", n => { NodeId = n.GetStringValue(); } },
                { "project_url", n => { ProjectUrl = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("archived_at", ArchivedAt);
            writer.WriteObjectValue<global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content>("content", Content);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.ProjectsV2ItemContentType>("content_type", ContentType);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::GFlow.GitHub.Models.SimpleUser>("creator", Creator);
            writer.WriteDoubleValue("id", Id);
            writer.WriteStringValue("item_url", ItemUrl);
            writer.WriteStringValue("node_id", NodeId);
            writer.WriteStringValue("project_url", ProjectUrl);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::GFlow.GitHub.Models.Issue"/>, <see cref="global::GFlow.GitHub.Models.ProjectsV2DraftIssue"/>, <see cref="global::GFlow.GitHub.Models.PullRequestSimple"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsV2ItemSimple_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Models.Issue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Models.Issue? Issue { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Models.Issue Issue { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Models.ProjectsV2DraftIssue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Models.ProjectsV2DraftIssue? ProjectsV2DraftIssue { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Models.ProjectsV2DraftIssue ProjectsV2DraftIssue { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Models.PullRequestSimple"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Models.PullRequestSimple? PullRequestSimple { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Models.PullRequestSimple PullRequestSimple { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::GFlow.GitHub.Models.ProjectsV2ItemSimple.ProjectsV2ItemSimple_content();
                if("issue".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Issue = new global::GFlow.GitHub.Models.Issue();
                }
                else if("projects-v2-draft-issue".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsV2DraftIssue = new global::GFlow.GitHub.Models.ProjectsV2DraftIssue();
                }
                else if("pull-request-simple".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PullRequestSimple = new global::GFlow.GitHub.Models.PullRequestSimple();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Issue != null)
                {
                    return Issue.GetFieldDeserializers();
                }
                else if(ProjectsV2DraftIssue != null)
                {
                    return ProjectsV2DraftIssue.GetFieldDeserializers();
                }
                else if(PullRequestSimple != null)
                {
                    return PullRequestSimple.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Issue != null)
                {
                    writer.WriteObjectValue<global::GFlow.GitHub.Models.Issue>(null, Issue);
                }
                else if(ProjectsV2DraftIssue != null)
                {
                    writer.WriteObjectValue<global::GFlow.GitHub.Models.ProjectsV2DraftIssue>(null, ProjectsV2DraftIssue);
                }
                else if(PullRequestSimple != null)
                {
                    writer.WriteObjectValue<global::GFlow.GitHub.Models.PullRequestSimple>(null, PullRequestSimple);
                }
            }
        }
    }
}
#pragma warning restore CS0618
