// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>
    /// Configuration for iteration fields.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsV2Field_configuration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The duration of the iteration in days.</summary>
        public int? Duration { get; set; }
        /// <summary>The iterations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GFlow.GitHub.Models.ProjectsV2IterationSettings>? Iterations { get; set; }
#nullable restore
#else
        public List<global::GFlow.GitHub.Models.ProjectsV2IterationSettings> Iterations { get; set; }
#endif
        /// <summary>The day of the week when the iteration starts.</summary>
        public int? StartDay { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Models.ProjectsV2Field_configuration"/> and sets the default values.
        /// </summary>
        public ProjectsV2Field_configuration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.ProjectsV2Field_configuration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.ProjectsV2Field_configuration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.ProjectsV2Field_configuration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "iterations", n => { Iterations = n.GetCollectionOfObjectValues<global::GFlow.GitHub.Models.ProjectsV2IterationSettings>(global::GFlow.GitHub.Models.ProjectsV2IterationSettings.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_day", n => { StartDay = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("duration", Duration);
            writer.WriteCollectionOfObjectValues<global::GFlow.GitHub.Models.ProjectsV2IterationSettings>("iterations", Iterations);
            writer.WriteIntValue("start_day", StartDay);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
