// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>
    /// A field inside a projects v2 project
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsV2Field : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Configuration for iteration fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GFlow.GitHub.Models.ProjectsV2Field_configuration? Configuration { get; set; }
#nullable restore
#else
        public global::GFlow.GitHub.Models.ProjectsV2Field_configuration Configuration { get; set; }
#endif
        /// <summary>The time when the field was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The field&apos;s data type.</summary>
        public global::GFlow.GitHub.Models.ProjectsV2Field_data_type? DataType { get; set; }
        /// <summary>The unique identifier of the field.</summary>
        public int? Id { get; set; }
        /// <summary>The ID of the issue field.</summary>
        public int? IssueFieldId { get; set; }
        /// <summary>The name of the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The node ID of the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeId { get; set; }
#nullable restore
#else
        public string NodeId { get; set; }
#endif
        /// <summary>The options available for single select fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GFlow.GitHub.Models.ProjectsV2SingleSelectOptions>? Options { get; set; }
#nullable restore
#else
        public List<global::GFlow.GitHub.Models.ProjectsV2SingleSelectOptions> Options { get; set; }
#endif
        /// <summary>The API URL of the project that contains the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectUrl { get; set; }
#nullable restore
#else
        public string ProjectUrl { get; set; }
#endif
        /// <summary>The time when the field was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Models.ProjectsV2Field"/> and sets the default values.
        /// </summary>
        public ProjectsV2Field()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.ProjectsV2Field"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.ProjectsV2Field CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.ProjectsV2Field();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configuration", n => { Configuration = n.GetObjectValue<global::GFlow.GitHub.Models.ProjectsV2Field_configuration>(global::GFlow.GitHub.Models.ProjectsV2Field_configuration.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "data_type", n => { DataType = n.GetEnumValue<global::GFlow.GitHub.Models.ProjectsV2Field_data_type>(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "issue_field_id", n => { IssueFieldId = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "node_id", n => { NodeId = n.GetStringValue(); } },
                { "options", n => { Options = n.GetCollectionOfObjectValues<global::GFlow.GitHub.Models.ProjectsV2SingleSelectOptions>(global::GFlow.GitHub.Models.ProjectsV2SingleSelectOptions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "project_url", n => { ProjectUrl = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::GFlow.GitHub.Models.ProjectsV2Field_configuration>("configuration", Configuration);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.ProjectsV2Field_data_type>("data_type", DataType);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("issue_field_id", IssueFieldId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("node_id", NodeId);
            writer.WriteCollectionOfObjectValues<global::GFlow.GitHub.Models.ProjectsV2SingleSelectOptions>("options", Options);
            writer.WriteStringValue("project_url", ProjectUrl);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
