// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>
    /// Pull Request Merge Async Result
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PullRequestMergeAsyncResult : ApiException, IParsable
    {
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details? Details { get; set; }
#nullable restore
#else
        public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details Details { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>The status property</summary>
        public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_status? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.PullRequestMergeAsyncResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.PullRequestMergeAsyncResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "details", n => { Details = n.GetObjectValue<global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details>(global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details>("details", Details);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_status>("status", Status);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember1"/>, <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember2"/>, <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember3"/>, <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember4"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PullRequestMergeAsyncResult_details : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember1? PullRequestMergeAsyncResultDetailsMember1 { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember1 PullRequestMergeAsyncResultDetailsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember2? PullRequestMergeAsyncResultDetailsMember2 { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember2 PullRequestMergeAsyncResultDetailsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember3? PullRequestMergeAsyncResultDetailsMember3 { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember3 PullRequestMergeAsyncResultDetailsMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember4? PullRequestMergeAsyncResultDetailsMember4 { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember4 PullRequestMergeAsyncResultDetailsMember4 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::GFlow.GitHub.Models.PullRequestMergeAsyncResult.PullRequestMergeAsyncResult_details();
                result.PullRequestMergeAsyncResultDetailsMember1 = new global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember1();
                result.PullRequestMergeAsyncResultDetailsMember2 = new global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember2();
                result.PullRequestMergeAsyncResultDetailsMember3 = new global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember3();
                result.PullRequestMergeAsyncResultDetailsMember4 = new global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember4();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PullRequestMergeAsyncResultDetailsMember1 != null || PullRequestMergeAsyncResultDetailsMember2 != null || PullRequestMergeAsyncResultDetailsMember3 != null || PullRequestMergeAsyncResultDetailsMember4 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(PullRequestMergeAsyncResultDetailsMember1, PullRequestMergeAsyncResultDetailsMember2, PullRequestMergeAsyncResultDetailsMember3, PullRequestMergeAsyncResultDetailsMember4);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::GFlow.GitHub.Models.PullRequestMergeAsyncResult_detailsMember1>(null, PullRequestMergeAsyncResultDetailsMember1, PullRequestMergeAsyncResultDetailsMember2, PullRequestMergeAsyncResultDetailsMember3, PullRequestMergeAsyncResultDetailsMember4);
            }
        }
    }
}
#pragma warning restore CS0618
