// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Models
{
    /// <summary>The lowest severity level at which code quality reviews need to be resolved before commits can be merged.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RepositoryRuleCodeQuality_parameters_severity
    {
        [EnumMember(Value = "errors")]
        #pragma warning disable CS1591
        Errors,
        #pragma warning restore CS1591
        [EnumMember(Value = "warnings")]
        #pragma warning disable CS1591
        Warnings,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes")]
        #pragma warning disable CS1591
        Notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
