// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bypass mode for the reviewer</summary>
        public global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers_mode? Mode { get; set; }
        /// <summary>The ID of the team or role selected as a bypass reviewer</summary>
        public int? ReviewerId { get; set; }
        /// <summary>The type of the bypass reviewer</summary>
        public global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers_reviewer_type? ReviewerType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers"/> and sets the default values.
        /// </summary>
        public SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers()
        {
            AdditionalData = new Dictionary<string, object>();
            Mode = global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers_mode.ALWAYS;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "mode", n => { Mode = n.GetEnumValue<global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers_mode>(); } },
                { "reviewer_id", n => { ReviewerId = n.GetIntValue(); } },
                { "reviewer_type", n => { ReviewerType = n.GetEnumValue<global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers_reviewer_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers_mode>("mode", Mode);
            writer.WriteIntValue("reviewer_id", ReviewerId);
            writer.WriteEnumValue<global::GFlow.GitHub.Models.SecurityAndAnalysis_secret_scanning_delegated_bypass_options_reviewers_reviewer_type>("reviewer_type", ReviewerType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
