// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Repos.Item.Item.Copilot.CloudAgent;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GFlow.GitHub.Repos.Item.Item.Copilot
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\copilot
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopilotRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cloudAgent property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Copilot.CloudAgent.CloudAgentRequestBuilder CloudAgent
        {
            get => new global::GFlow.GitHub.Repos.Item.Item.Copilot.CloudAgent.CloudAgentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/copilot", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/copilot", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
