// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Agents.Repos.Item.Item.Tasks.Item
{
    /// <summary>
    /// A GitHub resource (pull request, issue, etc.)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTask_GetResponse_artifacts_dataMember1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>GraphQL global ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GlobalId { get; set; }
#nullable restore
#else
        public string GlobalId { get; set; }
#endif
        /// <summary>GitHub resource ID</summary>
        public long? Id { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Agents.Repos.Item.Item.Tasks.Item.WithTask_GetResponse_artifacts_dataMember1"/> and sets the default values.
        /// </summary>
        public WithTask_GetResponse_artifacts_dataMember1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Agents.Repos.Item.Item.Tasks.Item.WithTask_GetResponse_artifacts_dataMember1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Agents.Repos.Item.Item.Tasks.Item.WithTask_GetResponse_artifacts_dataMember1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Agents.Repos.Item.Item.Tasks.Item.WithTask_GetResponse_artifacts_dataMember1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "global_id", n => { GlobalId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("global_id", GlobalId);
            writer.WriteLongValue("id", Id);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
