// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Enterprises.Item.CodeSecurity.Configurations.Item
{
    /// <summary>The enablement status of GitHub Advanced Security features. `enabled` will enable both Code Security and Secret Protection features.&gt; [!WARNING]&gt; `code_security` and `secret_protection` are deprecated values for this field. Prefer the individual `code_security` and `secret_protection` fields to set the status of these features.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithConfiguration_PatchRequestBody_advanced_security
    {
        [EnumMember(Value = "enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "code_security")]
        #pragma warning disable CS1591
        Code_security,
        #pragma warning restore CS1591
        [EnumMember(Value = "secret_protection")]
        #pragma warning disable CS1591
        Secret_protection,
        #pragma warning restore CS1591
    }
}
