// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrganizationsDeleteRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of custom property filters to match organizations. Organizations matching any of the specified property name/value pairs will be included. This is a one-time operation, setting the property on an organization in the future will not automatically update its coding agent policy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody_custom_properties>? CustomProperties { get; set; }
#nullable restore
#else
        public List<global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody_custom_properties> CustomProperties { get; set; }
#endif
        /// <summary>List of organization logins within the enterprise to disable Copilot cloud agent for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Organizations { get; set; }
#nullable restore
#else
        public List<string> Organizations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody"/> and sets the default values.
        /// </summary>
        public OrganizationsDeleteRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_properties", n => { CustomProperties = n.GetCollectionOfObjectValues<global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody_custom_properties>(global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody_custom_properties.CreateFromDiscriminatorValue)?.AsList(); } },
                { "organizations", n => { Organizations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::GFlow.GitHub.Enterprises.Item.Copilot.Policies.Coding_agent.Organizations.OrganizationsDeleteRequestBody_custom_properties>("custom_properties", CustomProperties);
            writer.WriteCollectionOfPrimitiveValues<string>("organizations", Organizations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
