// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Orgs.Item.PrivateRegistries.Item
{
    /// <summary>The authentication type for the private registry. This field cannot be changed after creation. If provided, it must match the existing `auth_type` of the configuration. To change the authentication type, delete and recreate the configuration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithSecret_namePatchRequestBody_auth_type
    {
        [EnumMember(Value = "token")]
        #pragma warning disable CS1591
        Token,
        #pragma warning restore CS1591
        [EnumMember(Value = "username_password")]
        #pragma warning disable CS1591
        Username_password,
        #pragma warning restore CS1591
        [EnumMember(Value = "oidc_azure")]
        #pragma warning disable CS1591
        Oidc_azure,
        #pragma warning restore CS1591
        [EnumMember(Value = "oidc_aws")]
        #pragma warning disable CS1591
        Oidc_aws,
        #pragma warning restore CS1591
        [EnumMember(Value = "oidc_jfrog")]
        #pragma warning disable CS1591
        Oidc_jfrog,
        #pragma warning restore CS1591
        [EnumMember(Value = "oidc_cloudsmith")]
        #pragma warning disable CS1591
        Oidc_cloudsmith,
        #pragma warning restore CS1591
        [EnumMember(Value = "oidc_gcp")]
        #pragma warning disable CS1591
        Oidc_gcp,
        #pragma warning restore CS1591
    }
}
