// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Orgs.Item.CopilotSpaces.Item
{
    /// <summary>The base role that determines default permissions for organization members. Changing this field requires admin permissions.- `no_access`: No default access (default)- `reader`: Organization members can read the space- `writer`: Organization members can read and edit the space- `admin`: Organization members have full admin access to the space</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithSpace_numberPutRequestBody_base_role
    {
        [EnumMember(Value = "reader")]
        #pragma warning disable CS1591
        Reader,
        #pragma warning restore CS1591
        [EnumMember(Value = "writer")]
        #pragma warning disable CS1591
        Writer,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_access")]
        #pragma warning disable CS1591
        No_access,
        #pragma warning restore CS1591
    }
}
