// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Models;
using GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\issues\{issue_number}\suggestions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuggestionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GFlow.GitHub.repos.item.item.issues.item.suggestions.item collection</summary>
        /// <param name="position">The unique identifier of the suggestion.</param>
        /// <returns>A <see cref="global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.Item.WithSuggestion_ItemRequestBuilder"/></returns>
        public global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.Item.WithSuggestion_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("suggestion_id", position);
                return new global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.Item.WithSuggestion_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the GFlow.GitHub.repos.item.item.issues.item.suggestions.item collection</summary>
        /// <param name="position">The unique identifier of the suggestion.</param>
        /// <returns>A <see cref="global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.Item.WithSuggestion_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.Item.WithSuggestion_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("suggestion_id", position);
                return new global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.Item.WithSuggestion_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/issues/{issue_number}/suggestions{?action*,page*,per_page*,state*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/issues/{issue_number}/suggestions{?action*,page*,per_page*,state*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists the suggestions on an issue. A suggestion is an agent-proposed change to an issue&apos;s type, labels, fields, assignees, or closed state that a maintainer can approve or dismiss.By default only pending suggestions are returned. Use `state=all` to return suggestions in every state, or `state=&lt;state&gt;` to filter to a single state. Use `action=&lt;action&gt;` to return only suggestions for a specific change.This endpoint is only available while the issue suggestions feature is enabled for the repository, and only supports issues, not pull requests.Requires triage access to the repository.
        /// API method documentation <see href="https://docs.github.com/rest/issues/issues#list-issue-suggestions" />
        /// </summary>
        /// <returns>A List&lt;global::GFlow.GitHub.Models.IssueSuggestion&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.ValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::GFlow.GitHub.Models.IssueSuggestion>?> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::GFlow.GitHub.Models.IssueSuggestion>> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "422", global::GFlow.GitHub.Models.ValidationError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::GFlow.GitHub.Models.IssueSuggestion>(requestInfo, global::GFlow.GitHub.Models.IssueSuggestion.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Lists the suggestions on an issue. A suggestion is an agent-proposed change to an issue&apos;s type, labels, fields, assignees, or closed state that a maintainer can approve or dismiss.By default only pending suggestions are returned. Use `state=all` to return suggestions in every state, or `state=&lt;state&gt;` to filter to a single state. Use `action=&lt;action&gt;` to return only suggestions for a specific change.This endpoint is only available while the issue suggestions feature is enabled for the repository, and only supports issues, not pull requests.Requires triage access to the repository.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists the suggestions on an issue. A suggestion is an agent-proposed change to an issue&apos;s type, labels, fields, assignees, or closed state that a maintainer can approve or dismiss.By default only pending suggestions are returned. Use `state=all` to return suggestions in every state, or `state=&lt;state&gt;` to filter to a single state. Use `action=&lt;action&gt;` to return only suggestions for a specific change.This endpoint is only available while the issue suggestions feature is enabled for the repository, and only supports issues, not pull requests.Requires triage access to the repository.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SuggestionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter suggestions by the change they propose.</summary>
            [Obsolete("This property is deprecated, use ActionAsGetActionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("action")]
            public string? Action { get; set; }
#nullable restore
#else
            [QueryParameter("action")]
            public string Action { get; set; }
#endif
            /// <summary>Filter suggestions by the change they propose.</summary>
            [QueryParameter("action")]
            public global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.GetActionQueryParameterType? ActionAsGetActionQueryParameterType { get; set; }
            /// <summary>The page number of the results to fetch. For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of results per page (max 100). For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>Filter suggestions by their state.</summary>
            [Obsolete("This property is deprecated, use StateAsGetStateQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
            /// <summary>Filter suggestions by their state.</summary>
            [QueryParameter("state")]
            public global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.GetStateQueryParameterType? StateAsGetStateQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SuggestionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
