// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Models;
using GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields
{
    /// <summary>
    /// Builds and executes requests for operations under \users\{username-id}\projectsV2\{project_number}\fields
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FieldsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GFlow.GitHub.users.item.projectsV2.item.fields.item collection</summary>
        /// <param name="position">The unique identifier of the field.</param>
        /// <returns>A <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.Item.WithField_ItemRequestBuilder"/></returns>
        public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.Item.WithField_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("field_id", position);
                return new global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.Item.WithField_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the GFlow.GitHub.users.item.projectsV2.item.fields.item collection</summary>
        /// <param name="position">The unique identifier of the field.</param>
        /// <returns>A <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.Item.WithField_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.Item.WithField_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("field_id", position);
                return new global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.Item.WithField_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{username%2Did}/projectsV2/{project_number}/fields{?after*,before*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{username%2Did}/projectsV2/{project_number}/fields{?after*,before*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// List all fields for a specific user-owned project.
        /// API method documentation <see href="https://docs.github.com/rest/projects/fields#list-project-fields-for-user" />
        /// </summary>
        /// <returns>A List&lt;global::GFlow.GitHub.Models.ProjectsV2Field&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::GFlow.GitHub.Models.ProjectsV2Field>?> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::GFlow.GitHub.Models.ProjectsV2Field>> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::GFlow.GitHub.Models.ProjectsV2Field>(requestInfo, global::GFlow.GitHub.Models.ProjectsV2Field.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Add a field to a specified user owned project.
        /// API method documentation <see href="https://docs.github.com/rest/projects/fields#add-field-to-user-owned-project" />
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.ProjectsV2Field"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.ValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GFlow.GitHub.Models.ProjectsV2Field?> PostAsync(global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GFlow.GitHub.Models.ProjectsV2Field> PostAsync(global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "422", global::GFlow.GitHub.Models.ValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GFlow.GitHub.Models.ProjectsV2Field>(requestInfo, global::GFlow.GitHub.Models.ProjectsV2Field.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all fields for a specific user-owned project.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Add a field to a specified user owned project.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember1"/>, <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember2"/>, <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FieldsPostRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember1? FieldsPostRequestBodyMember1 { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember1 FieldsPostRequestBodyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember2? FieldsPostRequestBodyMember2 { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember2 FieldsPostRequestBodyMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember3? FieldsPostRequestBodyMember3 { get; set; }
#nullable restore
#else
            public global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember3 FieldsPostRequestBodyMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsPostRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsPostRequestBody();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FieldsPostRequestBodyMember1 != null)
                {
                    return FieldsPostRequestBodyMember1.GetFieldDeserializers();
                }
                else if(FieldsPostRequestBodyMember2 != null)
                {
                    return FieldsPostRequestBodyMember2.GetFieldDeserializers();
                }
                else if(FieldsPostRequestBodyMember3 != null)
                {
                    return FieldsPostRequestBodyMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(FieldsPostRequestBodyMember1 != null)
                {
                    writer.WriteObjectValue<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember1>(null, FieldsPostRequestBodyMember1);
                }
                else if(FieldsPostRequestBodyMember2 != null)
                {
                    writer.WriteObjectValue<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember2>(null, FieldsPostRequestBodyMember2);
                }
                else if(FieldsPostRequestBodyMember3 != null)
                {
                    writer.WriteObjectValue<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsPostRequestBodyMember3>(null, FieldsPostRequestBodyMember3);
                }
            }
        }
        /// <summary>
        /// List all fields for a specific user-owned project.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FieldsRequestBuilderGetQueryParameters 
        {
            /// <summary>A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("after")]
            public string? After { get; set; }
#nullable restore
#else
            [QueryParameter("after")]
            public string After { get; set; }
#endif
            /// <summary>A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("before")]
            public string? Before { get; set; }
#nullable restore
#else
            [QueryParameter("before")]
            public string Before { get; set; }
#endif
            /// <summary>The number of results per page (max 100). For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FieldsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields.FieldsRequestBuilder.FieldsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FieldsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
