// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Users.Item.ProjectsV2.Item.Fields
{
    /// <summary>The field&apos;s data type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FieldsPostRequestBodyMember2_data_type
    {
        [EnumMember(Value = "single_select")]
        #pragma warning disable CS1591
        Single_select,
        #pragma warning restore CS1591
    }
}
