// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Sub
{
    /// <summary>
    /// Actions OIDC Subject customization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubPutRequestBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of unique strings. Each claim key can only contain alphanumeric characters and underscores.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IncludeClaimKeys { get; set; }
#nullable restore
#else
        public List<string> IncludeClaimKeys { get; set; }
#endif
        /// <summary>Whether to opt in to the immutable OIDC subject claim format for the organization. When `true`, new OIDC tokens will use a stable, repository-ID-based `sub` claim instead of the name-based format.</summary>
        public bool? UseImmutableSubject { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Sub.SubPutRequestBody"/> and sets the default values.
        /// </summary>
        public SubPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Sub.SubPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Sub.SubPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Sub.SubPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "include_claim_keys", n => { IncludeClaimKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "use_immutable_subject", n => { UseImmutableSubject = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("include_claim_keys", IncludeClaimKeys);
            writer.WriteBoolValue("use_immutable_subject", UseImmutableSubject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
