// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithBudget_PatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The budget_alerting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody_budget_alerting? BudgetAlerting { get; set; }
#nullable restore
#else
        public global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody_budget_alerting BudgetAlerting { get; set; }
#endif
        /// <summary>The budget amount in whole dollars. For license-based products, this represents the number of licenses.</summary>
        public int? BudgetAmount { get; set; }
        /// <summary>The date the budget will expire in `YYYY-MM-DD` format. Only dates in the future are accepted.If not set, the budget will not expire. Setting to `null` or `0` will remove the expiration date from a budget if set.Only supported for existing user-scoped budgets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at? ExpiresAt { get; set; }
#nullable restore
#else
        public global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at ExpiresAt { get; set; }
#endif
        /// <summary>Whether to prevent additional spending once the budget is exceeded. For budgets with `user` or `multi_user_customer` scope, this must remain `true`.</summary>
        public bool? PreventFurtherUsage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody"/> and sets the default values.
        /// </summary>
        public WithBudget_PatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "budget_alerting", n => { BudgetAlerting = n.GetObjectValue<global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody_budget_alerting>(global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody_budget_alerting.CreateFromDiscriminatorValue); } },
                { "budget_amount", n => { BudgetAmount = n.GetIntValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetObjectValue<global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at>(global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at.CreateFromDiscriminatorValue); } },
                { "prevent_further_usage", n => { PreventFurtherUsage = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody_budget_alerting>("budget_alerting", BudgetAlerting);
            writer.WriteIntValue("budget_amount", BudgetAmount);
            writer.WriteObjectValue<global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at>("expires_at", ExpiresAt);
            writer.WriteBoolValue("prevent_further_usage", PreventFurtherUsage);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="Date"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBudget_PatchRequestBody_expires_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="Date"/></summary>
            public Date? DateOnly { get; set; }
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::GFlow.GitHub.Organizations.Item.Settings.Billing.Budgets.Item.WithBudget_PatchRequestBody.WithBudget_PatchRequestBody_expires_at();
                if(parseNode.GetDateValue() is Date dateOnlyValue)
                {
                    result.DateOnly = dateOnlyValue;
                }
                else if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateOnly != null)
                {
                    writer.WriteDateValue(null, DateOnly);
                }
                else if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
            }
        }
    }
}
#pragma warning restore CS0618
