// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NetworkConfigurationsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The hosted compute service to use for the network configuration.</summary>
        public global::GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations.NetworkConfigurationsPostRequestBody_compute_service? ComputeService { get; set; }
        /// <summary>Indicates whether the failover network resource is enabled.</summary>
        public bool? FailoverNetworkEnabled { get; set; }
        /// <summary>A list of identifiers of the failover network settings resources to use for the network configuration. Exactly one resource identifier must be specified in the list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FailoverNetworkSettingsIds { get; set; }
#nullable restore
#else
        public List<string> FailoverNetworkSettingsIds { get; set; }
#endif
        /// <summary>Name of the network configuration. Must be between 1 and 100 characters and may only contain upper and lowercase letters a-z, numbers 0-9, &apos;.&apos;, &apos;-&apos;, and &apos;_&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A list of identifiers of the network settings resources to use for the network configuration. Exactly one resource identifier must be specified in the list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NetworkSettingsIds { get; set; }
#nullable restore
#else
        public List<string> NetworkSettingsIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations.NetworkConfigurationsPostRequestBody"/> and sets the default values.
        /// </summary>
        public NetworkConfigurationsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations.NetworkConfigurationsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations.NetworkConfigurationsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations.NetworkConfigurationsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compute_service", n => { ComputeService = n.GetEnumValue<global::GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations.NetworkConfigurationsPostRequestBody_compute_service>(); } },
                { "failover_network_enabled", n => { FailoverNetworkEnabled = n.GetBoolValue(); } },
                { "failover_network_settings_ids", n => { FailoverNetworkSettingsIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "network_settings_ids", n => { NetworkSettingsIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::GFlow.GitHub.Orgs.Item.Settings.NetworkConfigurations.NetworkConfigurationsPostRequestBody_compute_service>("compute_service", ComputeService);
            writer.WriteBoolValue("failover_network_enabled", FailoverNetworkEnabled);
            writer.WriteCollectionOfPrimitiveValues<string>("failover_network_settings_ids", FailoverNetworkSettingsIds);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("network_settings_ids", NetworkSettingsIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
