// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GFlow.GitHub.Repos.Item.Item.Codespaces.Machines
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\codespaces\machines
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MachinesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MachinesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/codespaces/machines{?client_ip*,location*,ref*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MachinesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/codespaces/machines{?client_ip*,location*,ref*}", rawUrl)
        {
        }
        /// <summary>
        /// List the machine types available for a given repository based on its configuration.OAuth app tokens and personal access tokens (classic) need the `codespace` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/rest/codespaces/machines#list-available-machine-types-for-a-repository" />
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesGetResponse?> GetAsMachinesGetResponseAsync(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder.MachinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesGetResponse> GetAsMachinesGetResponseAsync(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder.MachinesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "500", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesGetResponse>(requestInfo, global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List the machine types available for a given repository based on its configuration.OAuth app tokens and personal access tokens (classic) need the `codespace` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/rest/codespaces/machines#list-available-machine-types-for-a-repository" />
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsMachinesGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesResponse?> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder.MachinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesResponse> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder.MachinesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "500", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesResponse>(requestInfo, global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List the machine types available for a given repository based on its configuration.OAuth app tokens and personal access tokens (classic) need the `codespace` scope to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder.MachinesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder.MachinesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List the machine types available for a given repository based on its configuration.OAuth app tokens and personal access tokens (classic) need the `codespace` scope to use this endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MachinesRequestBuilderGetQueryParameters 
        {
            /// <summary>IP for location auto-detection when proxying a request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("client_ip")]
            public string? ClientIp { get; set; }
#nullable restore
#else
            [QueryParameter("client_ip")]
            public string ClientIp { get; set; }
#endif
            /// <summary>The location to check for available machines. Assigned by IP if not provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("location")]
            public string? Location { get; set; }
#nullable restore
#else
            [QueryParameter("location")]
            public string Location { get; set; }
#endif
            /// <summary>The branch or commit to check for prebuild availability and devcontainer restrictions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ref")]
            public string? Ref { get; set; }
#nullable restore
#else
            [QueryParameter("ref")]
            public string Ref { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MachinesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GFlow.GitHub.Repos.Item.Item.Codespaces.Machines.MachinesRequestBuilder.MachinesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
