// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Repos.Item.Item.Issues.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithIssue_numberPatchResponse_suggestions_state : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The confidence property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state_confidence? Confidence { get; set; }
        /// <summary>The duplicate_issue_id property</summary>
        public int? DuplicateIssueId { get; set; }
        /// <summary>The ignored property</summary>
        public bool? Ignored { get; set; }
        /// <summary>The ignored_reason property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state_ignored_reason? IgnoredReason { get; set; }
        /// <summary>The rationale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rationale { get; set; }
#nullable restore
#else
        public string Rationale { get; set; }
#endif
        /// <summary>The state_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateReason { get; set; }
#nullable restore
#else
        public string StateReason { get; set; }
#endif
        /// <summary>The suggest property</summary>
        public bool? Suggest { get; set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state"/> and sets the default values.
        /// </summary>
        public WithIssue_numberPatchResponse_suggestions_state()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "confidence", n => { Confidence = n.GetEnumValue<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state_confidence>(); } },
                { "duplicate_issue_id", n => { DuplicateIssueId = n.GetIntValue(); } },
                { "ignored", n => { Ignored = n.GetBoolValue(); } },
                { "ignored_reason", n => { IgnoredReason = n.GetEnumValue<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state_ignored_reason>(); } },
                { "rationale", n => { Rationale = n.GetStringValue(); } },
                { "state_reason", n => { StateReason = n.GetStringValue(); } },
                { "suggest", n => { Suggest = n.GetBoolValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state_confidence>("confidence", Confidence);
            writer.WriteIntValue("duplicate_issue_id", DuplicateIssueId);
            writer.WriteBoolValue("ignored", Ignored);
            writer.WriteEnumValue<global::GFlow.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberPatchResponse_suggestions_state_ignored_reason>("ignored_reason", IgnoredReason);
            writer.WriteStringValue("rationale", Rationale);
            writer.WriteStringValue("state_reason", StateReason);
            writer.WriteBoolValue("suggest", Suggest);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
