// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Repos.Item.Item.Stats.Code_frequency;
using GFlow.GitHub.Repos.Item.Item.Stats.Commit_activity;
using GFlow.GitHub.Repos.Item.Item.Stats.Contributors;
using GFlow.GitHub.Repos.Item.Item.Stats.Participation;
using GFlow.GitHub.Repos.Item.Item.Stats.Punch_card;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GFlow.GitHub.Repos.Item.Item.Stats
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\stats
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The code_frequency property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Stats.Code_frequency.Code_frequencyRequestBuilder Code_frequency
        {
            get => new global::GFlow.GitHub.Repos.Item.Item.Stats.Code_frequency.Code_frequencyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The commit_activity property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Stats.Commit_activity.Commit_activityRequestBuilder Commit_activity
        {
            get => new global::GFlow.GitHub.Repos.Item.Item.Stats.Commit_activity.Commit_activityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contributors property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Stats.Contributors.ContributorsRequestBuilder Contributors
        {
            get => new global::GFlow.GitHub.Repos.Item.Item.Stats.Contributors.ContributorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The participation property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Stats.Participation.ParticipationRequestBuilder Participation
        {
            get => new global::GFlow.GitHub.Repos.Item.Item.Stats.Participation.ParticipationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The punch_card property</summary>
        public global::GFlow.GitHub.Repos.Item.Item.Stats.Punch_card.Punch_cardRequestBuilder Punch_card
        {
            get => new global::GFlow.GitHub.Repos.Item.Item.Stats.Punch_card.Punch_cardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Stats.StatsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/stats", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Repos.Item.Item.Stats.StatsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/stats", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
