// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Repos.Item.Item.Pulls.Item.MergeAsync
{
    /// <summary>The merge method to use for a direct merge. Only supported for direct merges.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MergeAsyncPutRequestBody_merge_method
    {
        [EnumMember(Value = "merge")]
        #pragma warning disable CS1591
        Merge,
        #pragma warning restore CS1591
        [EnumMember(Value = "squash")]
        #pragma warning disable CS1591
        Squash,
        #pragma warning restore CS1591
        [EnumMember(Value = "rebase")]
        #pragma warning disable CS1591
        Rebase,
        #pragma warning restore CS1591
    }
}
