// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Repos.Item.Item.Pulls.Item.MergeAsync
{
    /// <summary>The action that will be taken to merge the pull request. `direct_merge` merges the pull request directly without using a merge queue; `merge_queue` adds the pull request to a merge queue; `default` uses a merge queue if one is configured for the target branch, or merges directly otherwise. If omitted, defaults to `default`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MergeAsyncPutRequestBody_merge_action
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "direct_merge")]
        #pragma warning disable CS1591
        Direct_merge,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge_queue")]
        #pragma warning disable CS1591
        Merge_queue,
        #pragma warning restore CS1591
    }
}
