// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Orgs.Item.ProjectsV2.Item.Fields
{
    /// <summary>The field&apos;s data type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FieldsPostRequestBodyMember4_data_type
    {
        [EnumMember(Value = "iteration")]
        #pragma warning disable CS1591
        Iteration,
        #pragma warning restore CS1591
    }
}
