// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Properties.Repo;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Properties
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org}\actions\oidc\customization\properties
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PropertiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The repo property</summary>
        public global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Properties.Repo.RepoRequestBuilder Repo
        {
            get => new global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Properties.Repo.RepoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/actions/oidc/customization/properties", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Orgs.Item.Actions.Oidc.Customization.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/actions/oidc/customization/properties", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
