// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\copilot\metrics\reports\repos-1-day
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Repos1DayRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Repos1DayRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/copilot/metrics/reports/repos-1-day?day={day}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Repos1DayRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/copilot/metrics/reports/repos-1-day?day={day}", rawUrl)
        {
        }
        /// <summary>
        /// Use this endpoint to retrieve download links for the Copilot enterprise repository report for a specific day. The report provides per-repository pull request metrics for Copilot across the enterprise, with one entry per repository.The report contains repository-level pull request activity for the specified day, including the Copilot Coding Agent (CCA) and Copilot Code Review (CCR) breakdowns. Only repositories that had activity on the specified day are included. Reports are generated daily and made available for download through signed URLs with a limited expiration time.The response includes download links to the report files, along with the specific date of the report. The report covers a complete day for which data has been processed.Enterprise owners, billing managers, and authorized users with fine-grained &quot;View Enterprise Copilot Metrics&quot; permission can retrieve Copilot metrics reports for the enterprise. OAuth app tokens and personal access tokens (classic) need either the `manage_billing:copilot` or `read:enterprise` scopes to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/rest/copilot/copilot-usage-metrics#get-copilot-enterprise-repository-report-for-a-specific-day" />
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.CopilotUsageMetrics1DayReport"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GFlow.GitHub.Models.CopilotUsageMetrics1DayReport?> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder.Repos1DayRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GFlow.GitHub.Models.CopilotUsageMetrics1DayReport> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder.Repos1DayRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "500", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GFlow.GitHub.Models.CopilotUsageMetrics1DayReport>(requestInfo, global::GFlow.GitHub.Models.CopilotUsageMetrics1DayReport.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Use this endpoint to retrieve download links for the Copilot enterprise repository report for a specific day. The report provides per-repository pull request metrics for Copilot across the enterprise, with one entry per repository.The report contains repository-level pull request activity for the specified day, including the Copilot Coding Agent (CCA) and Copilot Code Review (CCR) breakdowns. Only repositories that had activity on the specified day are included. Reports are generated daily and made available for download through signed URLs with a limited expiration time.The response includes download links to the report files, along with the specific date of the report. The report covers a complete day for which data has been processed.Enterprise owners, billing managers, and authorized users with fine-grained &quot;View Enterprise Copilot Metrics&quot; permission can retrieve Copilot metrics reports for the enterprise. OAuth app tokens and personal access tokens (classic) need either the `manage_billing:copilot` or `read:enterprise` scopes to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder.Repos1DayRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder.Repos1DayRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Use this endpoint to retrieve download links for the Copilot enterprise repository report for a specific day. The report provides per-repository pull request metrics for Copilot across the enterprise, with one entry per repository.The report contains repository-level pull request activity for the specified day, including the Copilot Coding Agent (CCA) and Copilot Code Review (CCR) breakdowns. Only repositories that had activity on the specified day are included. Reports are generated daily and made available for download through signed URLs with a limited expiration time.The response includes download links to the report files, along with the specific date of the report. The report covers a complete day for which data has been processed.Enterprise owners, billing managers, and authorized users with fine-grained &quot;View Enterprise Copilot Metrics&quot; permission can retrieve Copilot metrics reports for the enterprise. OAuth app tokens and personal access tokens (classic) need either the `manage_billing:copilot` or `read:enterprise` scopes to use this endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Repos1DayRequestBuilderGetQueryParameters 
        {
            /// <summary>The day to request data for, in `YYYY-MM-DD` format.</summary>
            [QueryParameter("day")]
            public Date? Day { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Repos1DayRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GFlow.GitHub.Enterprises.Item.Copilot.Metrics.Reports.Repos1Day.Repos1DayRequestBuilder.Repos1DayRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
