// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GFlow.GitHub.Orgs.Item.Campaigns
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CampaignsPostRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The code scanning alerts to include in this campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody_code_scanning_alerts>? CodeScanningAlerts { get; set; }
#nullable restore
#else
        public List<global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody_code_scanning_alerts> CodeScanningAlerts { get; set; }
#endif
        /// <summary>The contact link of the campaign. Must be a URI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactLink { get; set; }
#nullable restore
#else
        public string ContactLink { get; set; }
#endif
        /// <summary>A description for the campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The end date and time of the campaign. The date must be in the future.</summary>
        public DateTimeOffset? EndsAt { get; set; }
        /// <summary>If true, will automatically generate issues for the campaign. The default is false.</summary>
        public bool? GenerateIssues { get; set; }
        /// <summary>The logins of the users to set as the campaign managers. At this time, only a single manager can be supplied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Managers { get; set; }
#nullable restore
#else
        public List<string> Managers { get; set; }
#endif
        /// <summary>The name of the campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The slugs of the teams to set as the campaign managers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TeamManagers { get; set; }
#nullable restore
#else
        public List<string> TeamManagers { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody"/> and sets the default values.
        /// </summary>
        public CampaignsPostRequestBody()
        {
            GenerateIssues = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code_scanning_alerts", n => { CodeScanningAlerts = n.GetCollectionOfObjectValues<global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody_code_scanning_alerts>(global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody_code_scanning_alerts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contact_link", n => { ContactLink = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "ends_at", n => { EndsAt = n.GetDateTimeOffsetValue(); } },
                { "generate_issues", n => { GenerateIssues = n.GetBoolValue(); } },
                { "managers", n => { Managers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "team_managers", n => { TeamManagers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::GFlow.GitHub.Orgs.Item.Campaigns.CampaignsPostRequestBody_code_scanning_alerts>("code_scanning_alerts", CodeScanningAlerts);
            writer.WriteStringValue("contact_link", ContactLink);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("ends_at", EndsAt);
            writer.WriteBoolValue("generate_issues", GenerateIssues);
            writer.WriteCollectionOfPrimitiveValues<string>("managers", Managers);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("team_managers", TeamManagers);
        }
    }
}
#pragma warning restore CS0618
