// <auto-generated/>
#pragma warning disable CS0618
using GFlow.GitHub.Models;
using GFlow.GitHub.User.Keys.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GFlow.GitHub.User.Keys
{
    /// <summary>
    /// Builds and executes requests for operations under \user\keys
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KeysRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GFlow.GitHub.user.keys.item collection</summary>
        /// <param name="position">The unique identifier of the key.</param>
        /// <returns>A <see cref="global::GFlow.GitHub.User.Keys.Item.WithKey_ItemRequestBuilder"/></returns>
        public global::GFlow.GitHub.User.Keys.Item.WithKey_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("key_id", position);
                return new global::GFlow.GitHub.User.Keys.Item.WithKey_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the GFlow.GitHub.user.keys.item collection</summary>
        /// <param name="position">The unique identifier of the key.</param>
        /// <returns>A <see cref="global::GFlow.GitHub.User.Keys.Item.WithKey_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::GFlow.GitHub.User.Keys.Item.WithKey_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("key_id", position);
                return new global::GFlow.GitHub.User.Keys.Item.WithKey_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.User.Keys.KeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeysRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/keys{?page*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GFlow.GitHub.User.Keys.KeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeysRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/keys{?page*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists the public SSH keys for the authenticated user&apos;s GitHub account.OAuth app tokens and personal access tokens (classic) need the `read:public_key` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/rest/users/keys#list-public-ssh-keys-for-the-authenticated-user" />
        /// </summary>
        /// <returns>A List&lt;global::GFlow.GitHub.Models.Key&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::GFlow.GitHub.Models.Key>?> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.User.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::GFlow.GitHub.Models.Key>> GetAsync(Action<RequestConfiguration<global::GFlow.GitHub.User.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::GFlow.GitHub.Models.Key>(requestInfo, global::GFlow.GitHub.Models.Key.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Adds a public SSH key to the authenticated user&apos;s GitHub account.OAuth app tokens and personal access tokens (classic) need the `write:public_key` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/rest/users/keys#create-a-public-ssh-key-for-the-authenticated-user" />
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.Models.Key"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::GFlow.GitHub.Models.ValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GFlow.GitHub.Models.Key?> PostAsync(global::GFlow.GitHub.User.Keys.KeysPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GFlow.GitHub.Models.Key> PostAsync(global::GFlow.GitHub.User.Keys.KeysPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GFlow.GitHub.Models.BasicError.CreateFromDiscriminatorValue },
                { "422", global::GFlow.GitHub.Models.ValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GFlow.GitHub.Models.Key>(requestInfo, global::GFlow.GitHub.Models.Key.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists the public SSH keys for the authenticated user&apos;s GitHub account.OAuth app tokens and personal access tokens (classic) need the `read:public_key` scope to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.User.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GFlow.GitHub.User.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Adds a public SSH key to the authenticated user&apos;s GitHub account.OAuth app tokens and personal access tokens (classic) need the `write:public_key` scope to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::GFlow.GitHub.User.Keys.KeysPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::GFlow.GitHub.User.Keys.KeysPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GFlow.GitHub.User.Keys.KeysRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GFlow.GitHub.User.Keys.KeysRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GFlow.GitHub.User.Keys.KeysRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists the public SSH keys for the authenticated user&apos;s GitHub account.OAuth app tokens and personal access tokens (classic) need the `read:public_key` scope to use this endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KeysRequestBuilderGetQueryParameters 
        {
            /// <summary>The page number of the results to fetch. For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of results per page (max 100). For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KeysRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GFlow.GitHub.User.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KeysRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
