// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GFlow.GitHub.Search.Issues
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSearch_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "semantic")]
        #pragma warning disable CS1591
        Semantic,
        #pragma warning restore CS1591
        [EnumMember(Value = "hybrid")]
        #pragma warning disable CS1591
        Hybrid,
        #pragma warning restore CS1591
    }
}
